on:
  push:
    branches:
      - main
    paths:
      - 'scribblings/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

# Add permissions needed for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure we don't run multiple deployments simultaneously
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10  # Prevent hung builds
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: install Racket
      uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.16'

    - name: cache Racket dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/racket
          ~/.local/share/racket
        key: ${{ runner.os }}-racket-${{ hashFiles('**/info.rkt') }}
        restore-keys: |
          ${{ runner.os }}-racket-

    - name: install base package
      run: raco pkg install --skip-installed --no-setup --auto --name akari-sicp

    - name: setup base package
      run: raco pkg setup --no-docs --auto akari-sicp

    - name: build scribblings
      run: scribble +m --redirect-main https://docs.racket-lang.org/ --htmls --dest ./docs ./scribblings/akari-sicp.scrbl

    - name: upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/akari-sicp

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    timeout-minutes: 5  # Deployment should be quick
    steps:
      - name: setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
